### ISSUE TITLE
Code of Conduct Comments 

### ISSUE THREAD

**Issue by HeloiseS** [fedhere/FASTlab#1]
Hello Frederica,

You asked for comments on your code of conduct, so I thought I'd pitch in if that's okay.
I put it in the google doc at the ink below:

https://docs.google.com/document/d/1pYYvZE5G_7O_UQQIffXZs2Ba3AFUANUiM5B-Xu-zh-c/edit?usp=sharing

I hope this helps!

Cheers,
Heloise

**Comment by fedhere** [comment]
thank you! your comments were great and I implemented, keeping in consideration the specific nature of the coc, which is exclusively for my own research group, so a bit different than any other coc I worked on before. YOur article on how to write a CoC is amazing!

**Comment by HeloiseS** [comment]
I'm so glad I could help !! And I'm so happy you liked my piece 😭 
I'll close this issue now 😄, best of luck with your group! And, once, again, great initiative.
